package NoDam.Demo.user.controller;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import NoDam.Demo.user.domain.User;
import NoDam.Demo.user.repository.UserRepository;
import NoDam.Demo.user.service.JWTService;
import NoDam.Demo.user.service.UserService;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.crypto.factory.PasswordEncoderFactories;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.TransactionCallback;
import org.springframework.transaction.support.TransactionTemplate;

// generated by AI

@WebMvcTest(UserController.class)
@Import({UserService.class, JWTService.class, UserControllerTest.TestConfig.class})
@AutoConfigureMockMvc(addFilters = false)
@TestPropertySource(properties = {
        "token.SECRET_KEY=testSecretKeyForTestCasesOnly1234567890abcdef",
        "token.ACCESS_EXPIRATION_SECOND=3600000",
        "token.REFRESH_EXPIRATION_SECOND=7200000"
})
class UserControllerTest {

    /**
     * UserService가 필요로 하는 인프라 빈(PasswordEncoder, TransactionTemplate)을 제공.
     * Repository만 @MockitoBean으로 mock.
     */
    @TestConfiguration
    static class TestConfig {
        @Bean
        public PasswordEncoder passwordEncoder() {
            return PasswordEncoderFactories.createDelegatingPasswordEncoder();
        }

        @Bean
        @SuppressWarnings("unchecked")
        public TransactionTemplate transactionTemplate() {
            TransactionTemplate tt = Mockito.mock(TransactionTemplate.class);
            when(tt.execute(any(TransactionCallback.class))).thenAnswer(invocation -> {
                TransactionCallback<?> callback = invocation.getArgument(0);
                return callback.doInTransaction(Mockito.mock(TransactionStatus.class));
            });
            return tt;
        }
    }

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JWTService jwtService;

    @MockitoBean
    private UserRepository userRepository;

    // ==================== 회원가입 ====================

    @Nested
    @DisplayName("POST /user/public/register")
    class Register {

        @Test
        @DisplayName("성공")
        void success() throws Exception {
            when(userRepository.findByEmail("new@test.com")).thenReturn(Optional.empty());
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
                User saved = invocation.getArgument(0);
                ReflectionTestUtils.setField(saved, "id", 1L);
                return saved;
            });

            Map<String, String> body = Map.of(
                    "email", "new@test.com",
                    "password", "password123",
                    "name", "테스터"
            );

            mockMvc.perform(post("/user/public/register")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isOk());
        }

        @Test
        @DisplayName("실패 - 이메일 누락 → 400")
        void failNoEmail() throws Exception {
            Map<String, String> body = Map.of(
                    "password", "password123",
                    "name", "테스터"
            );

            mockMvc.perform(post("/user/public/register")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("실패 - 중복 이메일 → 409")
        void failDuplicate() throws Exception {
            User existing = User.builder()
                    .email("dup@test.com")
                    .password("encoded")
                    .name("기존유저")
                    .build();
            when(userRepository.findByEmail("dup@test.com")).thenReturn(Optional.of(existing));

            Map<String, String> body = Map.of(
                    "email", "dup@test.com",
                    "password", "pw",
                    "name", "이름"
            );

            mockMvc.perform(post("/user/public/register")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isConflict());
        }
    }

    // ==================== 로그인 ====================

    @Nested
    @DisplayName("POST /user/public/login")
    class Login {

        @Test
        @DisplayName("성공 - accessToken, refreshToken 반환")
        void success() throws Exception {
            String rawPassword = "password123";
            String encoded = passwordEncoder.encode(rawPassword);

            User user = User.builder()
                    .email("test@test.com")
                    .password(encoded)
                    .name("테스터")
                    .build();
            ReflectionTestUtils.setField(user, "id", 1L);

            when(userRepository.findByEmail("test@test.com")).thenReturn(Optional.of(user));

            Map<String, String> body = Map.of(
                    "email", "test@test.com",
                    "password", rawPassword
            );

            mockMvc.perform(post("/user/public/login")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.body.accessToken").isNotEmpty())
                    .andExpect(jsonPath("$.body.refreshToken").isNotEmpty());
        }

        @Test
        @DisplayName("실패 - 이메일 누락 → 400")
        void failNoEmail() throws Exception {
            Map<String, String> body = Map.of("password", "password123");

            mockMvc.perform(post("/user/public/login")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("실패 - 존재하지 않는 유저 → 404")
        void failUserNotFound() throws Exception {
            when(userRepository.findByEmail("notfound@test.com")).thenReturn(Optional.empty());

            Map<String, String> body = Map.of(
                    "email", "notfound@test.com",
                    "password", "pw"
            );

            mockMvc.perform(post("/user/public/login")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isNotFound());
        }

        @Test
        @DisplayName("실패 - 비밀번호 불일치 → 409")
        void failWrongPassword() throws Exception {
            User user = User.builder()
                    .email("test@test.com")
                    .password(passwordEncoder.encode("correctPassword"))
                    .name("테스터")
                    .build();

            when(userRepository.findByEmail("test@test.com")).thenReturn(Optional.of(user));

            Map<String, String> body = Map.of(
                    "email", "test@test.com",
                    "password", "wrongPassword"
            );

            mockMvc.perform(post("/user/public/login")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isConflict());
        }
    }

    // ==================== 토큰 재발급 ====================

    @Nested
    @DisplayName("POST /user/public/token-refresh")
    class TokenRefresh {

        @Test
        @DisplayName("성공 - 새 토큰 반환")
        void success() throws Exception {
            // 실제 JWTService로 refresh 토큰 생성
            String refreshToken = jwtService.generateRefreshToken(1L);

            Map<String, String> body = Map.of("token", refreshToken);

            mockMvc.perform(post("/user/public/token-refresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.accessToken").isNotEmpty())
                    .andExpect(jsonPath("$.refreshToken").isNotEmpty());
        }

        @Test
        @DisplayName("실패 - 토큰 누락 → 400")
        void failNoToken() throws Exception {
            mockMvc.perform(post("/user/public/token-refresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{}"))
                    .andDo(print())
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("실패 - 유효하지 않은 refresh 토큰 → 409")
        void failInvalidToken() throws Exception {
            Map<String, String> body = Map.of("token", "invalid.jwt.token");

            mockMvc.perform(post("/user/public/token-refresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(body)))
                    .andDo(print())
                    .andExpect(status().isConflict());
        }
    }
}
