package NoDam.Demo.plan.service;

import NoDam.Demo.common.type.*;
import NoDam.Demo.common.util.DateUtil;
import NoDam.Demo.place.dto.PlaceInfo;
import NoDam.Demo.place.service.PlaceSelectService;
import NoDam.Demo.plan.domain.DatePlan;
import NoDam.Demo.plan.domain.Plan;
import NoDam.Demo.plan.dto.request.DatePlanRequestDto;
import NoDam.Demo.plan.dto.request.PlacePlanRequestDto;
import NoDam.Demo.region.domain.Region;
import NoDam.Demo.region.service.RegionQueryService;
import NoDam.Demo.trip.domain.Trip;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

@Service
@RequiredArgsConstructor
public class AutoCreatePlanService {

    private final PlanCreateService planCreateService;
    private final PlanSelectService planSelectService;
    private final PlaceSelectService placeSelectService;
    private final RegionQueryService regionQueryService;

    @Async
    public CompletableFuture<List<DatePlan>> autoGenerateDatePlans(
            Trip trip,
            List<String> necessaryRegionCodes, // can empty
            List<String> necessaryGoogleCodes
    ) {
        List<DatePlan> tripDates = planSelectService.findAllDatePlan(trip);

        if(tripDates == null || !tripDates.isEmpty())
            return CompletableFuture.completedFuture(trip.getDatePlans()); // 멱등성 처리

        // start create Date plans
        List<DatePlan> createdDatePlans = new ArrayList<>();
        planCreateService.updateTripStatus(trip, true);

        for(TripThemeType theme : TripThemeType.values()) {
            List<DatePlanRequestDto> datePlanCreateDtos = recommendDatePlan(trip, theme, null, null);
            createdDatePlans.addAll(planCreateService.createDatePlans(trip, datePlanCreateDtos));
        }

        planCreateService.updateTripStatus(trip, false);

        return CompletableFuture.completedFuture(createdDatePlans);
    }

    @Async
    public CompletableFuture<List<DatePlan>> autoGenerateAllPlans(Trip trip) {
        List<DatePlan> createdDatePlan = new ArrayList<>();

        planCreateService.updateTripStatus(trip, true);

        for(DatePlan datePlan : planSelectService.findAllDatePlan(trip)) {
            List<PlacePlanRequestDto> plans = recommendPlans(trip, datePlan, WeatherType.SNOWY); // todo : weather
            createdDatePlan.add(planCreateService.createPlans(datePlan, plans));
        }

        planCreateService.updateTripStatus(trip, false);

        return CompletableFuture.completedFuture(createdDatePlan);
    }

    @Async
    // 일별 모든 장소 재 생성 (한번에 모두 생성)
    public CompletableFuture<DatePlan> autoGeneratePlans(
            Trip trip,
            DatePlan targetDate
    ) {
        planCreateService.updateTripStatus(trip, true);

        List<PlacePlanRequestDto> plans = recommendPlans(trip, targetDate, WeatherType.SNOWY); // todo : weather
        DatePlan createdPlans = planCreateService.createPlans(targetDate, plans);

        planCreateService.updateTripStatus(trip, false);

        return CompletableFuture.completedFuture(createdPlans);
    }

    private List<DatePlanRequestDto> recommendDatePlan(
            Trip trip,
            TripThemeType themeType,
            List<Region> necessaryRegions,
            List<String> necessaryGoogleIds
    ) {
        List<LocalDate> dates = DateUtil.toDateRange(trip.getStartDate(), trip.getEndDate());
        List<DatePlanRequestDto> datePlanCreateDtos = new ArrayList<>();

        for(int i = 0; i < dates.size(); i++) {
            // todo: selectedPlaceGoogleIds 일별 배정 로직 추가
            // todo : region 배정 일정 로직 추가
            datePlanCreateDtos.add(new DatePlanRequestDto(dates.get(i), 1L, themeType, ""));
        }

        return datePlanCreateDtos;
    }

    // 하루치 plan ai 생성
    private List<PlacePlanRequestDto> recommendPlans(
            Trip trip,
            DatePlan targetDate,
            WeatherType nowWeather
    ) {
        PriceType priceType = trip.getPriceType();
        SeasonType seasonType = null; // trip.getSeasonType(); todo : season 구현 필요
        TripThemeType themeType = targetDate.getTripThemeType();
        Region region = regionQueryService.findById(targetDate.getRegionId());

        ScheduleType scheduleType = trip.getScheduleType();

        // 장소 type 별 장소 10개 씩 주면서
        Map<PlaceType, List<PlaceInfo>> logicRecommendPlaceList = new HashMap<>();
        for(PlaceType placeType : PlaceType.values())
            logicRecommendPlaceList.put(placeType, recommendPlaces(placeType, priceType, region, seasonType, themeType, nowWeather, 10));

        // ai 에서 생성함
        List<PlacePlanRequestDto> placePlanRequestDtos = recommendWithAi(scheduleType, logicRecommendPlaceList);

        return placePlanRequestDtos;
    }

    private List<PlacePlanRequestDto> recommendWithAi(
            ScheduleType scheduleType,
            Map<PlaceType, List<PlaceInfo>> logicRecommendPlaceList
    ) {
        // 밥
        PlaceInfo bab = logicRecommendPlaceList.get(PlaceType.RESTAURANT).get(0);
        // 숙소
        PlaceInfo tnr = logicRecommendPlaceList.get(PlaceType.HOTEL).get(0);

        return List.of(
                new PlacePlanRequestDto(LocalTime.of(12,30), LocalTime.of(13,30), bab.getId()),
                new PlacePlanRequestDto(LocalTime.of(17,30), LocalTime.of(23,50), tnr.getId())
        );
    }

    private List<PlaceInfo> recommendPlaces(
            PlaceType placeType,
            PriceType priceType,
            Region region,
            SeasonType seasonType,
            TripThemeType themeType,
            WeatherType nowWeather,
            int count
    ) {
        return placeSelectService.selectPlace(
            placeType, region, priceType, seasonType, themeType, nowWeather, count
        )
                .stream()
                .map(PlaceInfo::of)
                .toList();
    }

}
