package NoDam.Demo.plan.service;

import NoDam.Demo.common.excetion.CustomException;
import NoDam.Demo.common.excetion.ErrorCode;
import NoDam.Demo.common.type.*;
import NoDam.Demo.common.util.DateUtil;
import NoDam.Demo.common.util.ListUtil;
import NoDam.Demo.place.domain.Place;
import NoDam.Demo.place.dto.PlaceInfo;
import NoDam.Demo.place.service.AirportSelectService;
import NoDam.Demo.place.service.GoogleApiService;
import NoDam.Demo.place.service.HotelRecommendService;
import NoDam.Demo.place.service.PlaceSelectService;
import NoDam.Demo.plan.domain.DatePlan;
import NoDam.Demo.plan.domain.PlacePlan;
import NoDam.Demo.plan.domain.TransportPlan;
import NoDam.Demo.plan.dto.request.DatePlanRequestDto;
import NoDam.Demo.plan.dto.request.PlacePlanRequestDto;
import NoDam.Demo.plan.dto.response.PlacePlanInfo;
import NoDam.Demo.plan.dto.response.RouteInfo;
import NoDam.Demo.region.domain.Region;
import NoDam.Demo.region.service.RegionQueryService;
import NoDam.Demo.trip.domain.Trip;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;
import java.util.function.Supplier;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AutoCreatePlanService {

    private final PlanCreateService planCreateService;
    private final PlanSelectService planSelectService;
    private final PlaceSelectService placeSelectService;
    private final RegionQueryService regionQueryService;
    private final GoogleApiService googleApiService;
    private final RegionAssignService regionAssignService;
    private final AirportSelectService airportSelectService;
    private final NecessaryPlaceDistributeService necessaryPlaceDistributeService;
    private final DayScheduleService dayScheduleService;
    private final HotelRecommendService hotelRecommendService;

    private final Logger logger = LoggerFactory.getLogger(AutoCreatePlanService.class);

    @Async
    public CompletableFuture<List<DatePlan>> autoGenerateDatePlans(
            Trip trip,
            List<String> necessaryRegionCodes,
            List<Place> necessaryPlaces,
            Place hotel,
            Place destinationAirport,
            LocalTime firstDayAirportTime,
            LocalTime lastDayAirportTime
    ) {
        List<DatePlan> tripDates = planSelectService.findAllDatePlan(trip);

        if (tripDates == null || !tripDates.isEmpty())
            return CompletableFuture.completedFuture(tripDates); // 멱등성 처리

        List<Region> necessaryRegions = regionQueryService.findRegionsByCode(necessaryRegionCodes);
        List<LocalDate> dates = DateUtil.toDateRange(trip.getStartDate(), trip.getEndDate());
        List<DatePlan> createdDatePlans = new ArrayList<>();

        trip = planCreateService.updateTripStatus(trip, true);

        // 1. Region 배정 (AI or fallback)
        Map<LocalDate, Region> dateRegionMap = regionAssignService.assign(
                dates, necessaryRegions, necessaryPlaces, destinationAirport, hotel);

        // 2. 공항 추천 - 사용자 입력 없을 때만
        Place airport = destinationAirport;
        if (airport == null) {
            Region firstRegion = dateRegionMap.get(dates.get(0));
            airport = airportSelectService.findAirportByRegion(firstRegion).orElse(null);
        }

        // 3. 필수 장소 날짜별 분배
        Map<LocalDate, List<Place>> necessaryPlacesByDate =
                necessaryPlaceDistributeService.distribute(necessaryPlaces, dates);

        // 4. DatePlan 생성 (TripThemeType별)
        final Place finalAirport = airport;
        for (TripThemeType theme : TripThemeType.values()) {
            List<DatePlanRequestDto> dtos = buildDatePlanDtos(
                    trip, theme, dates, dateRegionMap, necessaryPlacesByDate,
                    hotel, finalAirport, firstDayAirportTime, lastDayAirportTime);
            createdDatePlans.addAll(planCreateService.createDatePlans(trip, dtos));
        }

        trip = planCreateService.updateTripStatus(trip, false);
        return CompletableFuture.completedFuture(createdDatePlans);
    }

    private <T> T runWithPlanningLock(Trip trip, Supplier<T> task) {
        planCreateService.updateTripStatus(trip, true);
        try {
            T result = task.get();
            planCreateService.updateTripStatus(trip, false);
            return result;
        } catch (Exception e) {
            logger.error("planningLock 처리 중 에러 tripId={}", trip.getId(), e);
            planCreateService.forceUpdateTripStatus(trip, false);
            throw e;
        }
    }

    @Async
    public CompletableFuture<List<DatePlan>> autoGenerateAllPlans(Trip trip) {
        return runWithPlanningLock(trip, () -> {
        List<DatePlan> createdDatePlans = new ArrayList<>();
        List<Place> previousDaysPlaces = new ArrayList<>();

        for (DatePlan datePlan : planSelectService.findAllDatePlan(trip)) {
            PlanStatus status = datePlan.getPlanStatus();

            // AI 일정까지 완료된 날짜: previousDaysPlaces만 누적하고 skip
            if (status.isAfterOrEqual(PlanStatus.AI_PLANNED)) {
                previousDaysPlaces.addAll(getAiPlacesFromExistingPlans(datePlan));
                continue;
            }

            // 1. 공항 + 호텔 필수 PlacePlan 삽입
            if (status.isBefore(PlanStatus.FIXED_PLANNED)) {
                planCreateService.createPlans(datePlan, buildNecessaryPlans(trip, datePlan));
                planCreateService.updateDatePlanStatus(datePlan, PlanStatus.FIXED_PLANNED);
            }

            // 2. 후보 장소 조회 (HOTEL, AIRPORT 제외)
            Region region = regionQueryService.findById(datePlan.getRegionId());
            Map<PlaceType, List<PlaceInfo>> candidates = buildCandidates(trip, datePlan, region);

            // 3. 날짜에 배정된 필수 장소 조회
            List<PlaceInfo> necessaryPlaces = getNecessaryPlaces(datePlan);

            // 4. AI 일정 생성 (step 3+4 통합)
            List<PlacePlanInfo> fixedPlans = toPlacePlanInfos(planSelectService.findPlacePlansByDatePlan(datePlan));
            List<PlacePlanRequestDto> plans = dayScheduleService.buildSchedule(
                    trip.getScheduleType(), datePlan.getTripThemeType(),
                    necessaryPlaces, fixedPlans, candidates, previousDaysPlaces);
            List<Place> validatedPlaces = validatePlaces(plans);

            createdDatePlans.add(planCreateService.createPlans(datePlan, plans));
            planCreateService.updateDatePlanStatus(datePlan, PlanStatus.AI_PLANNED);
            previousDaysPlaces.addAll(validatedPlaces);

            // 5. hotel placeholder에 추천 호텔 배정
            if (datePlan.getHotelPlaceId() == null) {
                planSelectService.findEmptyPlacePlanByType(datePlan, PlaceType.HOTEL)
                        .ifPresent(placeholder -> {
                            List<Long> excludeIds = getPlacedPlaceIds(datePlan);
                            hotelRecommendService.recommend(region, trip.getPriceType(), excludeIds)
                                    .ifPresent(h -> planCreateService.updateHotelPlacePlanId(placeholder, h.getId()));
                        });
            }
            planCreateService.updateDatePlanStatus(datePlan, PlanStatus.HOTEL_ASSIGNED);
        }

        return CompletableFuture.completedFuture(createdDatePlans);
        });
    }

    // AI_PLANNED 이상인 날짜의 기존 PlacePlan에서 고정 장소(공항·호텔) 제외한 AI 선정 장소 반환
    private List<Place> getAiPlacesFromExistingPlans(DatePlan datePlan) {
        Set<Long> fixedIds = new HashSet<>();
        if (datePlan.getAirportPlaceId() != null) fixedIds.add(datePlan.getAirportPlaceId());
        if (datePlan.getHotelPlaceId() != null) fixedIds.add(datePlan.getHotelPlaceId());

        List<Long> aiPlaceIds = planSelectService.findPlacePlansByDatePlan(datePlan).stream()
                .map(PlacePlan::getPlaceId)
                .filter(id -> id != null && !fixedIds.contains(id))
                .distinct()
                .toList();

        return placeSelectService.findAllById(aiPlaceIds);
    }

    private List<Place> validatePlaces(List<PlacePlanRequestDto> aiResponse) {
        List<Long> placeIds = aiResponse.stream()
                .map(PlacePlanRequestDto::getPlaceId)
                .toList();
        List<Place> validPlaces = ListUtil.sortByRequestOrder(placeIds, placeSelectService.findAllById(placeIds), (p)->p.getId());

        if(validPlaces.contains(null))
            throw new CustomException(ErrorCode.API_FAIL);

        return validPlaces;
    }

    @Async
    // 일별 모든 장소 재 생성 (한번에 모두 생성)
    public CompletableFuture<DatePlan> autoGeneratePlans(Trip trip, DatePlan targetDate) {
        return runWithPlanningLock(trip, () -> {
            Region region = regionQueryService.findById(targetDate.getRegionId());
            Map<PlaceType, List<PlaceInfo>> candidates = buildCandidates(trip, targetDate, region);
            List<PlaceInfo> necessaryPlaces = getNecessaryPlaces(targetDate);
            List<PlacePlanInfo> fixedPlans = toPlacePlanInfos(planSelectService.findPlacePlansByDatePlan(targetDate));

            List<PlacePlanRequestDto> plans = dayScheduleService.buildSchedule(
                    trip.getScheduleType(), targetDate.getTripThemeType(),
                    necessaryPlaces, fixedPlans, candidates, List.of());
            validatePlaces(plans);

            DatePlan created = planCreateService.createPlans(targetDate, plans);
            planCreateService.updateDatePlanStatus(targetDate, PlanStatus.AI_PLANNED);
            return CompletableFuture.completedFuture(created);
        });
    }

    // 공항(첫날/마지막날), 호텔(매일) 필수 PlacePlan 생성
    private List<PlacePlanRequestDto> buildNecessaryPlans(Trip trip, DatePlan datePlan) {
        List<PlacePlanRequestDto> plans = new ArrayList<>();

        // 첫날: 도착 공항 (자정 ~ 공항 시간)
        if (datePlan.getAirportPlaceId() != null && datePlan.getAirportTime() != null
                && trip.getStartDate().equals(datePlan.getDate())) {
            plans.add(new PlacePlanRequestDto(LocalTime.MIDNIGHT, datePlan.getAirportTime(), datePlan.getAirportPlaceId()));
        }

        // 마지막날: 출발 공항 (공항 시간 ~ 23:59)
        if (datePlan.getAirportPlaceId() != null && datePlan.getAirportTime() != null
                && trip.getEndDate().equals(datePlan.getDate())) {
            plans.add(new PlacePlanRequestDto(datePlan.getAirportTime(), LocalTime.of(23, 59), datePlan.getAirportPlaceId()));
        }

        // 매일: 호텔 (not null → 실제 호텔, null → placeholder)
        plans.add(new PlacePlanRequestDto(LocalTime.of(20, 0), LocalTime.of(23, 50), datePlan.getHotelPlaceId()));

        return plans;
    }

    // 날짜에 배정된 필수 장소를 DatePlan.googleIds 기반으로 조회
    private List<PlaceInfo> getNecessaryPlaces(DatePlan datePlan) {
        String googleIds = datePlan.getGoogleIds();
        if (googleIds == null || googleIds.isBlank()) return List.of();
        List<String> ids = Arrays.asList(googleIds.split(","));
        return placeSelectService.findAllByGoogleId(ids).stream().map(PlaceInfo::of).toList();
    }

    // 후보 장소 조회 (HOTEL, AIRPORT는 직접 처리하므로 제외)
    private Map<PlaceType, List<PlaceInfo>> buildCandidates(Trip trip, DatePlan datePlan, Region region) {
        Map<PlaceType, List<PlaceInfo>> candidates = new HashMap<>();
        for (PlaceType placeType : PlaceType.values()) {
            if (placeType == PlaceType.HOTEL || placeType == PlaceType.AIRPORT) continue;
            candidates.put(placeType, placeSelectService.recommendPlaces(
                    placeType, region, trip.getPriceType(), null,
                    datePlan.getTripThemeType(), WeatherType.SUNNY, List.of(), 10)
                    .stream().map(PlaceInfo::of).toList());
        }
        return candidates;
    }

    // PlacePlan 엔티티 → PlacePlanInfo DTO 변환 (placeId null인 placeholder는 place 없이 시간만 포함)
    private List<PlacePlanInfo> toPlacePlanInfos(List<PlacePlan> placePlans) {
        Map<Long, Place> placeMap = placeSelectService.findAllById(
                placePlans.stream().map(PlacePlan::getPlaceId).filter(Objects::nonNull).distinct().toList()
        ).stream().collect(Collectors.toMap(Place::getId, p -> p));

        return placePlans.stream()
                .map(pp -> {
                    Place place = pp.getPlaceId() != null ? placeMap.get(pp.getPlaceId()) : null;
                    return place != null
                            ? PlacePlanInfo.of(pp, place)
                            : PlacePlanInfo.builder()
                                    .startTime(pp.getStartTime())
                                    .endTime(pp.getEndTime())
                                    .build();
                })
                .toList();
    }

    // 현재 DatePlan의 배정된 placeId 목록 (hotel 추천 exclude용)
    private List<Long> getPlacedPlaceIds(DatePlan datePlan) {
        return planSelectService.findPlacePlansByDatePlan(datePlan).stream()
                .map(PlacePlan::getPlaceId)
                .filter(Objects::nonNull)
                .toList();
    }

    private List<DatePlanRequestDto> buildDatePlanDtos(
            Trip trip,
            TripThemeType themeType,
            List<LocalDate> dates,
            Map<LocalDate, Region> dateRegionMap,
            Map<LocalDate, List<Place>> necessaryPlacesByDate,
            Place hotel,
            Place airport,
            LocalTime firstDayAirportTime,
            LocalTime lastDayAirportTime
    ) {
        Long hotelPlaceId = hotel != null ? hotel.getId() : null;
        Long airportPlaceId = airport != null ? airport.getId() : null;

        return dates.stream().map(date -> {
            Region region = dateRegionMap.get(date);
            List<Place> necessaryPlaces = necessaryPlacesByDate.getOrDefault(date, List.of());

            LocalTime airportTime = null;
            if (date.equals(trip.getStartDate())) airportTime = firstDayAirportTime;
            else if (date.equals(trip.getEndDate())) airportTime = lastDayAirportTime;

            Long dateAirportPlaceId = airportTime != null ? airportPlaceId : null;

            return new DatePlanRequestDto(date, region, themeType, necessaryPlaces,
                    hotelPlaceId, dateAirportPlaceId, airportTime);
        }).toList();
    }

    @Async
    public CompletableFuture<List<TransportPlan>> autoGenerateAllThemeTransportPlans(Trip trip, List<DatePlan> datePlans) {
        return runWithPlanningLock(trip, () -> {
            List<TransportPlan> allCreated = new ArrayList<>();

            for (DatePlan datePlan : datePlans) {
                if (datePlan.getPlanStatus().isAfterOrEqual(PlanStatus.TRANSPORT_PLANNED)) continue;
                allCreated.addAll(generateTransportPlans(datePlan));
                planCreateService.updateDatePlanStatus(datePlan, PlanStatus.TRANSPORT_PLANNED);
            }

            return CompletableFuture.completedFuture(allCreated);
        });
    }

    @Async
    // 동시성: 같은 PlacePlan 쌍에 동시 호출 시 중복 TransportPlan 생성 가능
    public CompletableFuture<List<TransportPlan>> createAllTransportPlan(Trip trip, DatePlan datePlan) {
        return runWithPlanningLock(trip, () -> {
            List<TransportPlan> transportPlans = generateTransportPlans(datePlan);
            return CompletableFuture.completedFuture(transportPlans);
        });
    }

    private List<TransportPlan> generateTransportPlans(DatePlan targetDate) {
        List<PlacePlan> placePlans = planSelectService.findPlacePlansByDatePlanWithTransport(targetDate)
                .stream()
                .sorted(Comparator.comparing(PlacePlan::getStartTime))
                .toList();

        List<Long> placeIds = placePlans.stream().map(PlacePlan::getPlaceId).filter(Objects::nonNull).distinct().toList();
        Map<Long, Place> placeMap = placeSelectService.findAllById(placeIds).stream()
                .collect(Collectors.toMap(Place::getId, p -> p));

        List<TransportPlan> transportPlans = new ArrayList<>();
        for (int i = 0; i < placePlans.size() - 1; i++) {
            PlacePlan current = placePlans.get(i);
            PlacePlan next = placePlans.get(i + 1);

            if (current.getDepartureTransport() != null) continue;
            if (current.getPlaceId() == null || next.getPlaceId() == null) continue;

            Place fromPlace = placeMap.get(current.getPlaceId());
            Place toPlace = placeMap.get(next.getPlaceId());
            if (fromPlace == null || toPlace == null) continue;

            RouteInfo routeInfo = googleApiService.computeRoutes(
                    fromPlace.getLat(), fromPlace.getLon(), toPlace.getLat(), toPlace.getLon());
            if (routeInfo == null) continue;

            transportPlans.add(TransportPlan.builder()
                    .fromPlacePlan(current)
                    .toPlacePlan(next)
                    .routeInfo(routeInfo)
                    .build());
        }

        return planCreateService.createTransportPlans(transportPlans);
    }

}
